Removes the cls. prefix for alt_auth_token and alt_project_id
The current code has those two fields prefixed with cls. on lines
79 and 80.  This causes the runtime errors:
AttributeError: type object '<someclass>' has no attribute 'alt_auth_token'
and
AttributeError: type object '<someclass>' has no attribute 'alt_project_id'

Change-Id: Ib8f52f50fe3d9eabe1c02d47ad7b7a13c6092133
Implements: blueprint cls-prefix